apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrollment-spa-api
  namespace: ENROLLMENT_APP_NAMESPACE
  labels:
    app: enrollment-spa-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: enrollment-spa-api
  template:
    metadata:
      labels:
        app: enrollment-spa-api
    spec:
      automountServiceAccountToken: false
      serviceAccountName: ENROLLMENT_SPA_API_SERVICEACCOUNT_NAME
      containers:
      - name: enrollment-spa-api
        image: ACR_NAME.azurecr.io/enrollmentspaapi:IMAGE_TAG
        ports:
        - containerPort: 8080
        env:
        - name: APPLICATION_CONFIGURATION_ENDPOINT
          value: "APP_CONFIG_ENDPOINT"
        - name: AllowedOrigins__0
          value: "*"
        envFrom:
        - configMapRef:
            name: app-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
            ephemeral-storage: "512Mi"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /weatherforecast
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /weatherforecast
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5