name: CI

on:
  pull_request:
    branches: [ master ]

env:
  DOTNET_VERSION: "10.0.x"
  NODE_VERSION: "22.x"
  PROJECT_NAME: "LogicBuilder.Samples.Enrollment.Spa.Flow"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: https://nuget.pkg.github.com/bpsLogicBuilder/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}

      - name: Install SonarQube Cloud scanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Begin SonarQube Cloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: "${{ format('BpsLogicBuilder_{0}', env.PROJECT_NAME) }}"
          SONAR_ORGANIZATION_KEY: "bpslogicbuilder"
        run: |
          dotnet-sonarscanner begin /k:"${{ env.SONAR_PROJECT_KEY }}" /o:"${{ env.SONAR_ORGANIZATION_KEY }}" /d:sonar.qualitygate.wait=true /d:sonar.token="${{ env.SONAR_TOKEN }}" /d:sonar.cs.vscoveragexml.reportsPaths="**/TestResults/coverage.xml" /d:sonar.coverage.exclusions="**/Enrollment.Domain/**,**/Enrollment.Data/**,**/Enrollment.Spa.Api/**"

      - name: Run unit tests
        run: |
          dotnet test Enrollment.Spa.Flow.Tests/Enrollment.Spa.Flow.Tests.csproj \
          --verbosity normal --configuration Release \
          --results-directory ./TestResults/ \
          -- \
          --coverage \
          --coverage-settings CodeCoverage.runsettings \
          --coverage-output-format xml \
          --coverage-output coverage.xml

      - name: End SonarQube Cloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet-sonarscanner end /d:sonar.token="${{ env.SONAR_TOKEN }}"

      - name: End SonarQube Cloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet-sonarscanner end /d:sonar.token="${{ env.SONAR_TOKEN }}"

      - name: Install dotnet-coverage
        run: dotnet tool install --global dotnet-coverage

      - name: Convert coverage to Cobertura
        run: dotnet-coverage merge ./TestResults/coverage.xml --output-format cobertura --output ./TestResults/coverage.cobertura.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./TestResults/coverage.cobertura.xml
          disable_search: true